codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: header, reach, changes, diff, files, footer
  require_changes: no
